#This class is created to upload the data files to the database
import os
import psycopg2
from process_data import file_processing

class data_upload:
    #This data is generated by the file_processing class
    get_cwd = os.getcwd()
    #processed_data = "/home/seeker/stash/my_projects/server_data_collector/datafiles"
    processed_data =get_cwd+"/datafiles"
    def __init__(self, servers_data_table, rpm_data_table, storage_table,
                 network_setup_table, network_interfaces_table, network_routes_table, lvm_setup_table, servers_path):
        self.file_list = [f for f in os.listdir(self.processed_data) if os.path.isfile(os.path.join(self.processed_data, f))]
        print(self.file_list)
        self.conn = psycopg2.connect(dbname='serverdata', user='seeker')
    def upload(self):
        os.chdir(self.processed_data)
        cur = self.conn.cursor()
        cur.execute("truncate a1servers cascade")
        for x in self.file_list:
            with open(x, 'r') as data_file:
                cur.copy_from(data_file, x, sep='|')
                print(x)
        self.conn.commit()
        self.conn.close()
