---
- name: Test connectivity on servers 
  wait_for:
    host: "{{ansible_host|default(inventory_hostname)}}"
    port: 22
    state: started
    timeout: 3

- name: gather facts
  setup:
    gather_subset:
       - 'all'
